### ISSUE TITLE
Can not build on unity 2021.3.3 for android Vulkan

### ISSUE THREAD

**Issue by IsfakurRahman** [Zallist/unity-universal-shadergraph-extensions#11]
Shader error in 'Shader Graphs/LavaShader2': 'SafeNormalize': no matching 1 parameter function at /Users/isfaq/Workspace/Thunder/GrassRoller/GrassRoller/Library/PackageCache/com.unity.render-pipelines.universal@12.1.6/Editor/ShaderGraph/Includes/PBRGBufferPass.hlsl(26) (on vulkan)

Compiling Subshader: 0, Pass: Pass 1, Vertex program with FOG_LINEAR _GBUFFER_NORMALS_OCT _MAIN_LIGHT_SHADOWS_CASCADE _MIXED_LIGHTING_SUBTRACTIVE
Platform defines: SHADER_API_MOBILE UNITY_ASTC_NORMALMAP_ENCODING UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_RGBM_ENCODING UNITY_NO_CUBEMAP_ARRAY UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_RGBM UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION
Disabled keywords: DIRLIGHTMAP_COMBINED DOTS_INSTANCING_ON DYNAMICLIGHTMAP_ON FOG_EXP FOG_EXP2 INSTANCING_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING SHADER_API_GLES30 UNITY_COLORSPACE_GAMMA UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF2 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_VIRTUAL_TEXTURING _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_SCREEN

**Comment by Zallist** [comment]
We don't even include pbrgbufferpass.hlsl in simple lit shaders anymore.
Are you running the latest version of the repo? 1.1.0

**Comment by IsfakurRahman** [comment]
Sorry I was running an old version. I just updated and it's working like a charm. Thanks for creating such a nice package.
