### ISSUE TITLE
Current version broken

### ISSUE THREAD

**Issue by bmourit** [Zallist/unity-universal-shadergraph-extensions#12]
Currently, the building breaks due to VFXShaderGraphSimpleLitGUI.cs appearing in two places.

1) [VFXShaderGraphSimpleLitGUI.cs](https://github.com/Zallist/unity-universal-shadergraph-extensions/blob/main/Editor/ShaderGUI/VFXShaderGraphSimpleLitGUI.cs) 

2) [VFXShaderGraphSimpleLitGUI.cs](https://github.com/Zallist/unity-universal-shadergraph-extensions/blob/main/Editor/VFXGraph/VFXShaderGraphSimpleLitGUI.cs)

**Comment by Zallist** [comment]
That goddamn #if statement completely hid a duplicate file.
Thanks for fixing.
