### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by volkerku** [Zallist/unity-universal-shadergraph-extensions#15]
I get 18 errors after installation.
Library\PackageCache\com.zallist.universal-shadergraph-extensions@4721c0cbf1\Editor\ShaderGUI\ShaderGraphSimpleLitGUI.cs(5,30): error CS0234: The type or namespace name 'Universal' does not exist in the namespace 'Unity.Rendering' (are you missing an assembly reference?)
Library\PackageCache\com.zallist.universal-shadergraph-extensions@4721c0cbf1\Editor\ShaderGraph\Targets\UniversalSimpleLitSubTarget.cs(10,58): error CS0234: The type or namespace name 'SubShaderUtils' does not exist in the namespace 'UnityEditor.Rendering.Universal.ShaderGraph' (are you missing an assembly reference?)
...
any idea?
Unity 202.3.31, URP 10.8.1

**Comment by Zallist** [comment]
Sorry, urp 10 and unity 2020 are not supported. There were huge changes between 10 and 12
